/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CodeLoader {
    }
    interface DataFetching {
    }
    interface DataFetchingFast {
    }
    interface RouterIndividual {
    }
    interface RouterOrdered {
    }
    interface RouterStandard {
    }
    interface SpinnerLoader {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCodeLoaderElement extends Components.CodeLoader, HTMLStencilElement {
    }
    var HTMLCodeLoaderElement: {
        prototype: HTMLCodeLoaderElement;
        new (): HTMLCodeLoaderElement;
    };
    interface HTMLDataFetchingElement extends Components.DataFetching, HTMLStencilElement {
    }
    var HTMLDataFetchingElement: {
        prototype: HTMLDataFetchingElement;
        new (): HTMLDataFetchingElement;
    };
    interface HTMLDataFetchingFastElement extends Components.DataFetchingFast, HTMLStencilElement {
    }
    var HTMLDataFetchingFastElement: {
        prototype: HTMLDataFetchingFastElement;
        new (): HTMLDataFetchingFastElement;
    };
    interface HTMLRouterIndividualElement extends Components.RouterIndividual, HTMLStencilElement {
    }
    var HTMLRouterIndividualElement: {
        prototype: HTMLRouterIndividualElement;
        new (): HTMLRouterIndividualElement;
    };
    interface HTMLRouterOrderedElement extends Components.RouterOrdered, HTMLStencilElement {
    }
    var HTMLRouterOrderedElement: {
        prototype: HTMLRouterOrderedElement;
        new (): HTMLRouterOrderedElement;
    };
    interface HTMLRouterStandardElement extends Components.RouterStandard, HTMLStencilElement {
    }
    var HTMLRouterStandardElement: {
        prototype: HTMLRouterStandardElement;
        new (): HTMLRouterStandardElement;
    };
    interface HTMLSpinnerLoaderElement extends Components.SpinnerLoader, HTMLStencilElement {
    }
    var HTMLSpinnerLoaderElement: {
        prototype: HTMLSpinnerLoaderElement;
        new (): HTMLSpinnerLoaderElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "code-loader": HTMLCodeLoaderElement;
        "data-fetching": HTMLDataFetchingElement;
        "data-fetching-fast": HTMLDataFetchingFastElement;
        "router-individual": HTMLRouterIndividualElement;
        "router-ordered": HTMLRouterOrderedElement;
        "router-standard": HTMLRouterStandardElement;
        "spinner-loader": HTMLSpinnerLoaderElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CodeLoader {
    }
    interface DataFetching {
    }
    interface DataFetchingFast {
    }
    interface RouterIndividual {
    }
    interface RouterOrdered {
    }
    interface RouterStandard {
    }
    interface SpinnerLoader {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "code-loader": CodeLoader;
        "data-fetching": DataFetching;
        "data-fetching-fast": DataFetchingFast;
        "router-individual": RouterIndividual;
        "router-ordered": RouterOrdered;
        "router-standard": RouterStandard;
        "spinner-loader": SpinnerLoader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "code-loader": LocalJSX.CodeLoader & JSXBase.HTMLAttributes<HTMLCodeLoaderElement>;
            "data-fetching": LocalJSX.DataFetching & JSXBase.HTMLAttributes<HTMLDataFetchingElement>;
            "data-fetching-fast": LocalJSX.DataFetchingFast & JSXBase.HTMLAttributes<HTMLDataFetchingFastElement>;
            "router-individual": LocalJSX.RouterIndividual & JSXBase.HTMLAttributes<HTMLRouterIndividualElement>;
            "router-ordered": LocalJSX.RouterOrdered & JSXBase.HTMLAttributes<HTMLRouterOrderedElement>;
            "router-standard": LocalJSX.RouterStandard & JSXBase.HTMLAttributes<HTMLRouterStandardElement>;
            "spinner-loader": LocalJSX.SpinnerLoader & JSXBase.HTMLAttributes<HTMLSpinnerLoaderElement>;
        }
    }
}
