/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface RouterIndividual {
    }
    interface RouterOrdered {
    }
    interface RouterStandard {
    }
    interface RouterStandardCode {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLRouterIndividualElement extends Components.RouterIndividual, HTMLStencilElement {
    }
    var HTMLRouterIndividualElement: {
        prototype: HTMLRouterIndividualElement;
        new (): HTMLRouterIndividualElement;
    };
    interface HTMLRouterOrderedElement extends Components.RouterOrdered, HTMLStencilElement {
    }
    var HTMLRouterOrderedElement: {
        prototype: HTMLRouterOrderedElement;
        new (): HTMLRouterOrderedElement;
    };
    interface HTMLRouterStandardElement extends Components.RouterStandard, HTMLStencilElement {
    }
    var HTMLRouterStandardElement: {
        prototype: HTMLRouterStandardElement;
        new (): HTMLRouterStandardElement;
    };
    interface HTMLRouterStandardCodeElement extends Components.RouterStandardCode, HTMLStencilElement {
    }
    var HTMLRouterStandardCodeElement: {
        prototype: HTMLRouterStandardCodeElement;
        new (): HTMLRouterStandardCodeElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "router-individual": HTMLRouterIndividualElement;
        "router-ordered": HTMLRouterOrderedElement;
        "router-standard": HTMLRouterStandardElement;
        "router-standard-code": HTMLRouterStandardCodeElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface RouterIndividual {
    }
    interface RouterOrdered {
    }
    interface RouterStandard {
    }
    interface RouterStandardCode {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "router-individual": RouterIndividual;
        "router-ordered": RouterOrdered;
        "router-standard": RouterStandard;
        "router-standard-code": RouterStandardCode;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "router-individual": LocalJSX.RouterIndividual & JSXBase.HTMLAttributes<HTMLRouterIndividualElement>;
            "router-ordered": LocalJSX.RouterOrdered & JSXBase.HTMLAttributes<HTMLRouterOrderedElement>;
            "router-standard": LocalJSX.RouterStandard & JSXBase.HTMLAttributes<HTMLRouterStandardElement>;
            "router-standard-code": LocalJSX.RouterStandardCode & JSXBase.HTMLAttributes<HTMLRouterStandardCodeElement>;
        }
    }
}
