/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CxOrderProps, CxProps } from "./types/types";
export namespace Components {
    interface ShiftHandler {
        "class": string | undefined;
        "criteria": any;
        "enter": CxProps['enter'];
        "enterReverse": CxProps['enterReverse'];
        "exit": CxProps['exit'];
        "exitReverse": CxProps['exitReverse'];
        "getChildConfig": () => CxOrderProps;
        "getJsx": () => any;
        "stableChild": string | undefined;
    }
    interface StPlayground {
    }
}
declare global {
    interface HTMLShiftHandlerElement extends Components.ShiftHandler, HTMLStencilElement {
    }
    var HTMLShiftHandlerElement: {
        prototype: HTMLShiftHandlerElement;
        new (): HTMLShiftHandlerElement;
    };
    interface HTMLStPlaygroundElement extends Components.StPlayground, HTMLStencilElement {
    }
    var HTMLStPlaygroundElement: {
        prototype: HTMLStPlaygroundElement;
        new (): HTMLStPlaygroundElement;
    };
    interface HTMLElementTagNameMap {
        "shift-handler": HTMLShiftHandlerElement;
        "st-playground": HTMLStPlaygroundElement;
    }
}
declare namespace LocalJSX {
    interface ShiftHandler {
        "class"?: string | undefined;
        "criteria": any;
        "enter": CxProps['enter'];
        "enterReverse"?: CxProps['enterReverse'];
        "exit": CxProps['exit'];
        "exitReverse"?: CxProps['exitReverse'];
        "getChildConfig": () => CxOrderProps;
        "getJsx": () => any;
        "stableChild"?: string | undefined;
    }
    interface StPlayground {
    }
    interface IntrinsicElements {
        "shift-handler": ShiftHandler;
        "st-playground": StPlayground;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shift-handler": LocalJSX.ShiftHandler & JSXBase.HTMLAttributes<HTMLShiftHandlerElement>;
            "st-playground": LocalJSX.StPlayground & JSXBase.HTMLAttributes<HTMLStPlaygroundElement>;
        }
    }
}
